"""MenuTree AutoQA -- crawl, reconstruct, measure, emit.

Exit codes (for CI gating):
    0  gate passed
    1  pipeline error (crawl/parse/emit failed)
    2  gate failed (coverage below threshold, or regression vs baseline)
"""
import argparse
import logging
import os
import sys
from datetime import datetime
from pathlib import Path

import yaml
from dotenv import load_dotenv

from src.analysis.coverage import CoverageAnalyzer
from src.crawler.droidbot_runner import CrawlError, DroidBotRunner
from src.generator.path_emitter import PathEmitter
from src.generator.uvta_writer import SuiteValidationError, UVTAWriter
from src.llm.inference import LLMEngine
from src.logging_setup import setup_logging
from src.parser.utg_parser import UTGParseError, UTGParser

logger = logging.getLogger("menutree")

EXIT_OK, EXIT_ERROR, EXIT_GATE_FAILED = 0, 1, 2


def load_config(path: str) -> dict:
    config_path = Path(path)
    if not config_path.exists():
        raise SystemExit(
            f"Config file '{path}' not found. Copy the template:\n"
            "    cp config.yaml.example config.yaml"
        )
    with open(config_path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="MenuTree AutoQA pipeline")
    parser.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    parser.add_argument(
        "--skip-crawl",
        action="store_true",
        help="Reuse existing droidbot_out data instead of crawling the device",
    )
    parser.add_argument(
        "--crawl-only",
        action="store_true",
        help="Run the exploration crawl and stop (no parsing or emission)",
    )
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Write this run's coverage report as the new gate baseline",
    )
    parser.add_argument(
        "--run-id",
        default=datetime.now().strftime("%Y%m%d_%H%M%S"),
        help="Identifier for this run (used in log and report filenames)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    load_dotenv()
    config = load_config(args.config)

    log_file = setup_logging(
        log_dir=config.get("logging", {}).get("dir", "./logs"),
        level=config.get("logging", {}).get("level", "INFO"),
        run_id=args.run_id,
    )

    package = os.getenv("TARGET_PACKAGE")
    serial = os.getenv("DEFAULT_SERIAL") or None
    if not package:
        logger.error("TARGET_PACKAGE is not set. Copy .env.example to .env.")
        return EXIT_ERROR

    logger.info("=" * 62)
    logger.info("  MenuTree AutoQA  |  run=%s  package=%s", args.run_id, package)
    logger.info("  log: %s", log_file.resolve())
    logger.info("=" * 62)

    crawler_cfg = config.get("crawler", {})
    parser_cfg = dict(config.get("parser", {}))
    parser_cfg.setdefault("output_dir", crawler_cfg.get("output_dir", "./droidbot_out"))

    # -- 1. Crawl --------------------------------------------------------
    if args.skip_crawl:
        logger.info("--skip-crawl set; reusing %s", parser_cfg["output_dir"])
    else:
        try:
            runner = DroidBotRunner(serial, package, crawler_cfg)
            if not runner.start_exploration():
                logger.error("Crawl produced no usable UTG; aborting.")
                return EXIT_ERROR
        except CrawlError as exc:
            logger.error("Crawl failed: %s", exc)
            return EXIT_ERROR

    if args.crawl_only:
        logger.info("--crawl-only set; stopping after exploration.")
        return EXIT_OK

    # -- 2. Reconstruct the MenuTree -------------------------------------
    try:
        tree = UTGParser(parser_cfg).parse()
    except UTGParseError as exc:
        logger.error("Could not reconstruct the MenuTree: %s", exc)
        return EXIT_ERROR

    # -- 3. Emit testcases deterministically -----------------------------
    generator_cfg = config.get("generator", {})
    emitter = PathEmitter(generator_cfg, package)
    cases = emitter.emit(tree)

    if not cases:
        logger.error(
            "No testcases could be emitted from %d transition(s). "
            "The crawl likely never entered the app.",
            len(tree.transitions),
        )
        return EXIT_ERROR

    # -- 4. Optional LLM naming pass (never structural) -------------------
    cases = LLMEngine(config.get("llm", {})).rename_testcases(cases, package)

    # -- 5. Write the suite ----------------------------------------------
    # Deliberately free of run id, timestamp and absolute paths: the suite must
    # be byte-identical for identical crawl data so CI can diff it. Per-run
    # provenance lives in the coverage report instead.
    header = (
        "# Generated by MenuTree AutoQA -- deterministic, derived from DroidBot UTG paths.\n"
        "# Do not hand-edit; regenerate from the crawl instead.\n"
        f"# Package: {package}\n"
        f"# Testcases: {len(cases)}"
    )
    try:
        UVTAWriter(generator_cfg).write_suite(cases, header_comment=header)
    except SuiteValidationError as exc:
        logger.error("Suite rejected: %s", exc)
        return EXIT_ERROR

    # -- 6. Coverage & gate ----------------------------------------------
    coverage_cfg = dict(config.get("coverage", {}))
    coverage_cfg.setdefault("apk_path", crawler_cfg.get("apk_path"))
    analyzer = CoverageAnalyzer(coverage_cfg)
    report = analyzer.analyze(tree, args.run_id, len(cases), emitter.skipped)

    report_path = Path(coverage_cfg.get("report_dir", "./reports")) / f"{args.run_id}.json"
    analyzer.write(report, report_path)
    logger.info(analyzer.summarize(report))

    failures = analyzer.evaluate_gate(report)

    if args.update_baseline and coverage_cfg.get("baseline_file"):
        analyzer.write(report, Path(coverage_cfg["baseline_file"]))
        logger.info("Baseline updated from this run.")

    if failures:
        logger.error("GATE FAILED (%d issue(s)):", len(failures))
        for failure in failures:
            logger.error("  - %s", failure)
        return EXIT_GATE_FAILED

    logger.info("GATE PASSED")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
